name: Deploy to OVHCloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin


      - name: Build Docker image
        run: docker build -t francis8t/ovhcloud-node-app .

      - name: Push Docker image to DockerHub
        run: docker push francis8t/ovhcloud-node-app

      - name: SSH to OVHCloud Instance and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.OVH_SERVER_IP }}
          username: ${{ secrets.OVH_SERVER_USERNAME }}
          key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker pull francis8t/ovhcloud-node-app
            docker stop ovhcloud-node-app || true
            docker rm ovhcloud-node-app || true
            docker run -d --name ovhcloud-node-app -p 80:3000 francis8t/ovhcloud-node-app

